# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/scrape.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/scrape.proto\x12\x06scrape\"*\n\rScrapeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"!\n\x0eScrapeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x13ScrapeStatusRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\'\n\x14ScrapeStatusResponse\x12\x0f\n\x07is_done\x18\x01 \x01(\x08\"!\n\x11ScrapeBlobRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\'\n\x12ScrapeBlobResponse\x12\x11\n\tjson_blob\x18\x01 \x01(\t2\xdf\x01\n\rScrapeService\x12\x37\n\x06Scrape\x12\x15.scrape.ScrapeRequest\x1a\x16.scrape.ScrapeResponse\x12K\n\x0eIsScrapingDone\x12\x1b.scrape.ScrapeStatusRequest\x1a\x1c.scrape.ScrapeStatusResponse\x12H\n\x0fGetScrapingBlob\x12\x19.scrape.ScrapeBlobRequest\x1a\x1a.scrape.ScrapeBlobResponseb\x06proto3')



_SCRAPEREQUEST = DESCRIPTOR.message_types_by_name['ScrapeRequest']
_SCRAPERESPONSE = DESCRIPTOR.message_types_by_name['ScrapeResponse']
_SCRAPESTATUSREQUEST = DESCRIPTOR.message_types_by_name['ScrapeStatusRequest']
_SCRAPESTATUSRESPONSE = DESCRIPTOR.message_types_by_name['ScrapeStatusResponse']
_SCRAPEBLOBREQUEST = DESCRIPTOR.message_types_by_name['ScrapeBlobRequest']
_SCRAPEBLOBRESPONSE = DESCRIPTOR.message_types_by_name['ScrapeBlobResponse']
ScrapeRequest = _reflection.GeneratedProtocolMessageType('ScrapeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPEREQUEST,
  '__module__' : 'proto.scrape_pb2'
  # @@protoc_insertion_point(class_scope:scrape.ScrapeRequest)
  })
_sym_db.RegisterMessage(ScrapeRequest)

ScrapeResponse = _reflection.GeneratedProtocolMessageType('ScrapeResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPERESPONSE,
  '__module__' : 'proto.scrape_pb2'
  # @@protoc_insertion_point(class_scope:scrape.ScrapeResponse)
  })
_sym_db.RegisterMessage(ScrapeResponse)

ScrapeStatusRequest = _reflection.GeneratedProtocolMessageType('ScrapeStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPESTATUSREQUEST,
  '__module__' : 'proto.scrape_pb2'
  # @@protoc_insertion_point(class_scope:scrape.ScrapeStatusRequest)
  })
_sym_db.RegisterMessage(ScrapeStatusRequest)

ScrapeStatusResponse = _reflection.GeneratedProtocolMessageType('ScrapeStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPESTATUSRESPONSE,
  '__module__' : 'proto.scrape_pb2'
  # @@protoc_insertion_point(class_scope:scrape.ScrapeStatusResponse)
  })
_sym_db.RegisterMessage(ScrapeStatusResponse)

ScrapeBlobRequest = _reflection.GeneratedProtocolMessageType('ScrapeBlobRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPEBLOBREQUEST,
  '__module__' : 'proto.scrape_pb2'
  # @@protoc_insertion_point(class_scope:scrape.ScrapeBlobRequest)
  })
_sym_db.RegisterMessage(ScrapeBlobRequest)

ScrapeBlobResponse = _reflection.GeneratedProtocolMessageType('ScrapeBlobResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPEBLOBRESPONSE,
  '__module__' : 'proto.scrape_pb2'
  # @@protoc_insertion_point(class_scope:scrape.ScrapeBlobResponse)
  })
_sym_db.RegisterMessage(ScrapeBlobResponse)

_SCRAPESERVICE = DESCRIPTOR.services_by_name['ScrapeService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCRAPEREQUEST._serialized_start=30
  _SCRAPEREQUEST._serialized_end=72
  _SCRAPERESPONSE._serialized_start=74
  _SCRAPERESPONSE._serialized_end=107
  _SCRAPESTATUSREQUEST._serialized_start=109
  _SCRAPESTATUSREQUEST._serialized_end=144
  _SCRAPESTATUSRESPONSE._serialized_start=146
  _SCRAPESTATUSRESPONSE._serialized_end=185
  _SCRAPEBLOBREQUEST._serialized_start=187
  _SCRAPEBLOBREQUEST._serialized_end=220
  _SCRAPEBLOBRESPONSE._serialized_start=222
  _SCRAPEBLOBRESPONSE._serialized_end=261
  _SCRAPESERVICE._serialized_start=264
  _SCRAPESERVICE._serialized_end=487
# @@protoc_insertion_point(module_scope)
