# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/scrape.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/scrape.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/scrape.proto\x12\x06scrape\"*\n\rScrapeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"!\n\x0eScrapeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x13ScrapeStatusRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\'\n\x14ScrapeStatusResponse\x12\x0f\n\x07is_done\x18\x01 \x01(\x08\"!\n\x11ScrapeBlobRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\'\n\x12ScrapeBlobResponse\x12\x11\n\tjson_blob\x18\x01 \x01(\t2\xdf\x01\n\rScrapeService\x12\x37\n\x06Scrape\x12\x15.scrape.ScrapeRequest\x1a\x16.scrape.ScrapeResponse\x12K\n\x0eIsScrapingDone\x12\x1b.scrape.ScrapeStatusRequest\x1a\x1c.scrape.ScrapeStatusResponse\x12H\n\x0fGetScrapingBlob\x12\x19.scrape.ScrapeBlobRequest\x1a\x1a.scrape.ScrapeBlobResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.scrape_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRAPEREQUEST']._serialized_start=30
  _globals['_SCRAPEREQUEST']._serialized_end=72
  _globals['_SCRAPERESPONSE']._serialized_start=74
  _globals['_SCRAPERESPONSE']._serialized_end=107
  _globals['_SCRAPESTATUSREQUEST']._serialized_start=109
  _globals['_SCRAPESTATUSREQUEST']._serialized_end=144
  _globals['_SCRAPESTATUSRESPONSE']._serialized_start=146
  _globals['_SCRAPESTATUSRESPONSE']._serialized_end=185
  _globals['_SCRAPEBLOBREQUEST']._serialized_start=187
  _globals['_SCRAPEBLOBREQUEST']._serialized_end=220
  _globals['_SCRAPEBLOBRESPONSE']._serialized_start=222
  _globals['_SCRAPEBLOBRESPONSE']._serialized_end=261
  _globals['_SCRAPESERVICE']._serialized_start=264
  _globals['_SCRAPESERVICE']._serialized_end=487
# @@protoc_insertion_point(module_scope)
